forms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-detail-form/',
     include('multi_step_form.urls', namespace='multi_step_form')),
    path('pdf-results/', include('pdf_results.urls', namespace='pdf_results'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multi_step_form/urls.py
from django.urls import path

from multi_step_form.views import FormStep1, FormStep2, FormStep3

app_name = 'multi_step_form'
urlpatterns = [
    path('', FormStep1.as_view(), name='step_1'),
    path('step-2', FormStep2.as_view(), name='step_2'),
    path('step-3', FormStep3.as_view(), name='step_3'),
]

multi_step_form/models.py
from django.db import models

# Create your models here.


class UserPictures(models.Model):
    '''
    Model to manage multiple pictures of the user
    '''
    user_uuid = models.UUIDField()
    image = models.ImageField(upload_to='user_images/')

multi_step_form/forms.py
from django import forms

class Step1Form(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=50)
    last_name = forms.CharField(label='Last Name', max_length=50)


class Step2Form(forms.Form):
    local_address = forms.CharField(label='Local Address', max_length=200)
    permanent_address = forms.CharField(label='Permanent Address',
             max_length=200)

class Step3Form(forms.Form):
    images = forms.ImageField(widget=forms.ClearableFileInput(
        attrs={'multiple': True}))
    
   

multi_step_form/views.py
from django.shortcuts import render
from uuid import uuid4
from django.views.generic import FormView
from django.urls import reverse_lazy
from multi_step_form.models import UserPictures
from multi_step_form.forms import Step1Form, Step2Form, Step3Form

# Create your views here.
class FormStep1(FormView):
    form_class = Step1Form
    success_url = reverse_lazy('multi_step_form:step_2')
    template_name = 'multi_step_form/step1.html'

    def get_initial(self):
        initials = super(FormStep1, self).get_initial()
        initials.update({
            'first_name': self.request.session.get('first_name', None),
            'last_name': self.request.session.get('last_name', None),
        })
        return initials
    
    def form_valid(self, form):
        post_data = self.request.POST
        if form.is_valid():
            self.request.session['first_name'] = post_data['first_name']
            self.request.session['last_name'] = post_data['last_name']
            if not self.request.session.get('user_uuid', None):
                self.request.session['user_uuid'] = str(uuid4())
        return super(FormStep1, self).form_valid(form)
        
        

class FormStep2(FormView):
    form_class = Step2Form
    success_url = reverse_lazy('multi_step_form:step_3')
    template_name = 'multi_step_form/step2.html'

    def get_initial(self):
        initials = super(FormStep2, self).get_initial()
        initials.update({
            'local_address': self.request.session.get('local_address', None),
            'permanent_address': self.request.session.get('permanent_address', None),
        })
        return initials
    
    def form_valid(self, form):
        post_data = self.request.POST
        if form.is_valid():
            self.request.session['local_address'] = post_data['local_address']
            self.request.session['permanent_address'] = post_data['permanent_address']
        return super(FormStep2, self).form_valid(form)


class FormStep3(FormView):
    form_class = Step3Form
    success_url = reverse_lazy('pdf_results:pdf')
    template_name = 'multi_step_form/step3.html'

    def get_context_data(self, **kwargs):
        context_data = super(FormStep3, self).get_context_data(**kwargs)
        user_uuid = self.request.session.get('user_uuid')
        context_data['user_images'] = UserPictures.objects.filter(
            user_uuid=user_uuid)
        return context_data
    
    
    def form_valid(self, form):
        request_files = self.request.FILES.getlist('images')
        if form.is_valid():
            user_uuid = self.request.session.get('user_uuid')
            # clear the last user pictures
            UserPictures.objects.filter(
                user_uuid=user_uuid).delete()
            for image in request_files:
                UserPictures.objects.create(user_uuid=user_uuid,
                    image=image)
        return super(FormStep3, self).form_valid(form)

multi_step_form/templates/multi_step_form/step1.html
{% extends 'layouts/base.html' %}
{% block body %}
<h1>User detail form: Step 1</h1>
<form method="POST" name="step1_form">
    {% csrf_token %}
    <div >
        <label for="first_name">First Name</label>
        <input type="text"  name="first_name" {% if form.first_name.value %}value="{{form.first_name.value}}"{% endif %}>
        {% for error in form.first_name.errors %}
        <p>{{error}}</p>
        {% endfor %}
    </div>
    <label for="last_name">Last Name</label>
    <input type="text" name="last_name" {% if form.last_name.value %}value="{{form.last_name.value}}"{% endif %}>
    {% for error in form.last_name.errors %}
    <p>{{error}}</p>
    {% endfor %}
    
    <div >
        <input type="submit" value="Next">
    </div>
</form>
{% endblock body %}

multi_step_form/templates/multi_step_form/step2.html
{% extends 'layouts/base.html' %}
{% block body %}
<h1>User detail form: Step 2</h1>
<form method="POST" name="step2_form">
        {% csrf_token %}
    <div >
        <label for="local_address">Local Address</label>
        <input type="text" name="local_address" {% if form.local_address.value %}value="{{form.local_address.value}}"{% endif %}>
        {% for error in form.local_address.errors %}
        <p>{{error}}</p>
        {% endfor %}
    </div>
    <label for="permanent_address">Permanent Address</label>
    <input type="text" name="permanent_address" {% if form.permanent_address.value %}value="{{form.permanent_address.value}}"{% endif %}>
    {% for error in form.permanent_address.errors %}
    <p>{{error}}</p>
    {% endfor %}
    
    <div >
        <a href="{% url 'multi_step_form:step_1' %}">Back</a>
        <input type="submit" value="Next">
    </div>
</form>
{% endblock body %}

multi_step_form/templates/multi_step_form/step3.html
{% extends 'layouts/base.html' %}
{% block body %}
<h1>User detail form: Step 3</h1>
<form method="POST" name="step3_form" enctype="multipart/form-data">
        {% csrf_token %}
    {% if user_images %}
    <div>
        <h2>Last uploaded images</h2>
        {% for user_image in user_images %}
        <img src="{{user_image.image.url}}" alt="User Image">
        {% endfor %}
    </div>
    {% endif %}
    <div>
        <label for="images">User Images</label>
        <input type="file" name="images" multiple>
        {% for error in form.images.errors %}
        <p>{{error}}</p>
        {% endfor %}
    </div>
    
    <div >
        <a href="{% url 'multi_step_form:step_2' %}">Back</a>
        <input type="submit" value="Submit">
    </div>
</form>
{% endblock body %}